# https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/rose-pine.toml"
    # "~/.config/alacritty/themes/themes/seashells.toml" # Beach scheme
    # "~/.config/alacritty/themes/themes/dracula.toml"
    # "~/.config/alacritty/themes/themes/alabaster_dark.toml"
    # "~/.config/alacritty/themes/themes/thelovelace.toml"
    # "~/.config/alacritty/themes/themes/omni.toml" # purple
    # "~/.config/alacritty/themes/themes/everforest_dark.toml" # forest green
    # "~/.config/alacritty/themes/themes/inferno.toml" # red
    # "~/.config/alacritty/themes/themes/konsole_linux.toml"

    # "~/.config/alacritty/themes/themes/afterglow.toml"
    # ~/.config/alacritty/themes/themes/aura.toml"
    # "~/.config/alacritty/themes/themes/baitong.toml" #green (has colorhints err)
    # "~/.config/alacritty/themes/themes/carbonfox.toml"
    # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
    # "~/.config/alacritty/themes/themes/dark_pastels.toml"
    # "~/.config/alacritty/themes/themes/flat_remix.toml"
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/themes/horizon-dark.toml"
    # "~/.config/alacritty/themes/themes/marine_dark.toml"
    # "~/.config/alacritty/themes/themes/moonlight_ii_vscode.toml"
    # "~/.config/alacritty/themes/themes/one_dark.toml"
    # "~/.config/alacritty/themes/themes/smoooooth.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
    # "~/.config/alacritty/themes/themes/ubuntu.toml"

    # "~/.config/alacritty/themes/themes/pencil_light.toml" #white
    # "~/.config/alacritty/themes/themes/github_light.toml" #white
    # "~/.config/alacritty/themes/themes/github_light_high_contrast.toml" #white

]
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = {shape = "Block"}

[window]
decorations = "none"
decorations_theme_variant = "Dark"
# opacity = 1.0
opacity = 0.8
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5
